name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: yongki150/withbible
          stage: main
          yaml: >
            name: withbible-client
            
            app: web
            
            options:
              docbase: /build
              nodeversion: "16"
              spa: true
              buildenv:
                - name: REACT_APP_HOST
                  value: ${{ vars.REACT_APP_HOST }}                
                - name: REACT_APP_PUSHER_APP_KEY
                  value: ${{ secrets.REACT_APP_PUSHER_APP_KEY }}
                - name: REACT_APP_PUSHER_CLUSTER
                  value: ${{ secrets.REACT_APP_PUSHER_CLUSTER }}
                - name: REACT_APP_PUSHER_BEAMS_INSTANCE_ID
                  value: ${{ secrets.REACT_APP_PUSHER_BEAMS_INSTANCE_ID }}
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
